#  -*- mode: makefile -*-

PROJECT		= MuImage
TYPE		= LIBRARY

CXXFILES	= ImageModule ImageType PixelsType
LIBS            = MuLang Mu tiff jpeg cxcore cv gc 

include $(SRC_ROOT)/build/Makefile.master
