//
//  Copyright (c) 2009, Jim Hourihan
//  All rights reserved.
// 
//  Redistribution and use in source and binary forms, with or without
//  modification, are permitted provided that the following conditions
//  are met:
//
//     * Redistributions of source code must retain the above
//       copyright notice, this list of conditions and the following
//       disclaimer.
//
//     * Redistributions in binary form must reproduce the above
//       copyright notice, this list of conditions and the following
//       disclaimer in the documentation and/or other materials
//       provided with the distribution.
//
//     * Neither the name of the software nor the names of its
//       contributors may be used to endorse or promote products
//       derived from this software without specific prior written
//       permission.
// 
//  THIS SOFTWARE IS PROVIDED BY Jim Hourihan ''AS IS'' AND ANY EXPRESS
//  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
//  ARE DISCLAIMED. IN NO EVENT SHALL Jim Hourihan BE LIABLE FOR
//  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
//  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
//  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
//  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
//  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
//  DAMAGE.
//
#ifndef __MuQt__QPaintDeviceType__h__
#define __MuQt__QPaintDeviceType__h__
#include <iostream>
#include <Mu/Class.h>
#include <Mu/Process.h>
#include <QtCore/QtCore>
#include <QtGui/QtGui>
#include <QtWidgets/QtWidgets>
#include <QtNetwork/QtNetwork>
#include <QtWebKit/QtWebKit>
#include <QtWebKitWidgets/QtWebKitWidgets>
#include <QtSvg/QtSvg>
#include <MuQt5/Bridge.h>

namespace Mu {
class MuQt_QPaintDevice;

//
//  NOTE: file generated by qt2mu.py
//

class QPaintDeviceType : public Class
{
  public:

    struct Struct { QPaintDevice* object; };
    typedef MuQt_QPaintDevice MuQtType;
    typedef QPaintDevice QtType;

    //
    //  Constructors
    //

    QPaintDeviceType(Context* context, const char* name, Class* superClass = 0);
    virtual ~QPaintDeviceType();

    static bool isInheritable() { return true; }
    static inline ClassInstance* cachedInstance(const MuQtType*);

    //
    //  Class API
    //

    virtual void load();

    MemberFunction* _func[1];
};

// Inheritable object

class MuQt_QPaintDevice : public QPaintDevice
{
  public:
    virtual ~MuQt_QPaintDevice();
  protected:
    MuQt_QPaintDevice(Pointer muobj, const CallEnvironment*) ;
    virtual int metric(QPaintDevice::PaintDeviceMetric metric_) const;
  public:
    int metric_pub(QPaintDevice::PaintDeviceMetric metric_) const { return metric(metric_); }
    int metric_pub_parent(QPaintDevice::PaintDeviceMetric metric_) const { return QPaintDevice::metric(metric_); }
  public:
    const QPaintDeviceType* _baseType;
    ClassInstance* _obj;
    const CallEnvironment* _env;
};

inline ClassInstance* QPaintDeviceType::cachedInstance(const QPaintDeviceType::MuQtType* obj) { return obj->_obj; }

} // Mu

#endif // __MuQt__QPaintDeviceType__h__
