//
//  Copyright (c) 2009, Jim Hourihan
//  All rights reserved.
// 
//  Redistribution and use in source and binary forms, with or without
//  modification, are permitted provided that the following conditions
//  are met:
//
//     * Redistributions of source code must retain the above
//       copyright notice, this list of conditions and the following
//       disclaimer.
//
//     * Redistributions in binary form must reproduce the above
//       copyright notice, this list of conditions and the following
//       disclaimer in the documentation and/or other materials
//       provided with the distribution.
//
//     * Neither the name of the software nor the names of its
//       contributors may be used to endorse or promote products
//       derived from this software without specific prior written
//       permission.
// 
//  THIS SOFTWARE IS PROVIDED BY Jim Hourihan ''AS IS'' AND ANY EXPRESS
//  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
//  ARE DISCLAIMED. IN NO EVENT SHALL Jim Hourihan BE LIABLE FOR
//  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
//  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
//  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
//  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
//  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
//  DAMAGE.
//
#ifndef __MuQt__QSplitterType__h__
#define __MuQt__QSplitterType__h__
#include <iostream>
#include <Mu/Class.h>
#include <Mu/Process.h>
#include <QtCore/QtCore>
#include <QtGui/QtGui>
#include <QtWidgets/QtWidgets>
#include <QtNetwork/QtNetwork>
#include <QtWebKit/QtWebKit>
#include <QtWebKitWidgets/QtWebKitWidgets>
#include <QtSvg/QtSvg>
#include <MuQt5/Bridge.h>

namespace Mu {
class MuQt_QSplitter;

//
//  NOTE: file generated by qt2mu.py
//

class QSplitterType : public Class
{
  public:

    typedef MuQt_QSplitter MuQtType;
    typedef QSplitter QtType;

    //
    //  Constructors
    //

    QSplitterType(Context* context, 
           const char* name,
           Class* superClass = 0,
           Class* superClass2 = 0);

    virtual ~QSplitterType();

    static bool isInheritable() { return true; }
    static inline ClassInstance* cachedInstance(const MuQtType*);

    //
    //  Class API
    //

    virtual void load();

    MemberFunction* _func[6];
};

// Inheritable object

class MuQt_QSplitter : public QSplitter
{
  public:
    virtual ~MuQt_QSplitter();
    MuQt_QSplitter(Pointer muobj, const CallEnvironment*, QWidget * parent) ;
    MuQt_QSplitter(Pointer muobj, const CallEnvironment*, Qt::Orientation orientation, QWidget * parent) ;
    virtual QSize minimumSizeHint() const;
    virtual QSize sizeHint() const;
  protected:
    virtual void changeEvent(QEvent * ev) ;
    virtual bool event(QEvent * e) ;
    virtual void resizeEvent(QResizeEvent * _p14) ;
    virtual void paintEvent(QPaintEvent * _p13) ;
  public:
    int closestLegalPosition_pub(int pos, int index)  { return closestLegalPosition(pos, index); }
    int closestLegalPosition_pub_parent(int pos, int index)  { return QSplitter::closestLegalPosition(pos, index); }
    void moveSplitter_pub(int pos, int index)  { moveSplitter(pos, index); }
    void moveSplitter_pub_parent(int pos, int index)  { QSplitter::moveSplitter(pos, index); }
    void setRubberBand_pub(int pos)  { setRubberBand(pos); }
    void setRubberBand_pub_parent(int pos)  { QSplitter::setRubberBand(pos); }
    void changeEvent_pub(QEvent * ev)  { changeEvent(ev); }
    void changeEvent_pub_parent(QEvent * ev)  { QSplitter::changeEvent(ev); }
    bool event_pub(QEvent * e)  { return event(e); }
    bool event_pub_parent(QEvent * e)  { return QSplitter::event(e); }
    void resizeEvent_pub(QResizeEvent * _p14)  { resizeEvent(_p14); }
    void resizeEvent_pub_parent(QResizeEvent * _p14)  { QSplitter::resizeEvent(_p14); }
    void paintEvent_pub(QPaintEvent * _p13)  { paintEvent(_p13); }
    void paintEvent_pub_parent(QPaintEvent * _p13)  { QSplitter::paintEvent(_p13); }
  public:
    const QSplitterType* _baseType;
    ClassInstance* _obj;
    const CallEnvironment* _env;
};

inline ClassInstance* QSplitterType::cachedInstance(const QSplitterType::MuQtType* obj) { return obj->_obj; }

} // Mu

#endif // __MuQt__QSplitterType__h__
