#  -*- mode: makefile -*-

PROJECT      = gelato
TYPE         = PLUGIN
PLUGIN_DIR   = plugins/Mu
PLUGINSUFFIX = .so

CXXFILES     = init
LIBS         = MuGelato gc gelato

IPATH       += $(GELATOHOME)/include
LPATH       += $(GELATOHOME)/lib

include $(SRC_ROOT)/build/Makefile.master
