#  -*- mode: makefile -*-

PROJECT		= glu
TYPE		= PLUGIN
PLUGIN_DIR	= plugins/Mu
PLUGINSUFFIX	= .so
IPATH		= $(SRC_ROOT)/pub/gc

FRAMEWORKS_DARWIN = OpenGL

CXXFILES	= init
LIBS            = MuGLU

LIBS_LINUX      = GLU GL

include $(SRC_ROOT)/build/Makefile.master
