#  -*- mode: makefile -*-


PROJECT		= MuPy
TYPE		= LIBRARY

USES            = python

CXXFILES	= PyObjectType PyTypeObjectType PyModule
LIBS            = MuLang Mu GL gc Half atomic


include $(SRC_ROOT)/build/Makefile.master
