#  -*- mode: makefile -*-

PROJECT		= MuVarying
TYPE		= LIBRARY

CXXFILES   =	VaryingModule	VaryingTypeModifier			    \
		VaryingType	VaryingObject	    VaryingBoolType	    \
		VaryingVecfType VaryingFloatType    VaryingComponentType    \
		VaryingMath

LIBS = MuLang Mu gc 

include $(SRC_ROOT)/build/Makefile.master
