#  -*- mode: makefile -*-

PROJECT		= autodoc
TYPE		= PLUGIN
PLUGIN_DIR	= plugins/Mu
PLUGINSUFFIX	= .so
IPATH		= $(SRC_ROOT)/pub/gc

CXXFILES	= init
LIBS            = MuAutoDoc 

include $(SRC_ROOT)/build/Makefile.master
