//
//  Copyright (c) 2009, Jim Hourihan
//  All rights reserved.
// 
//  Redistribution and use in source and binary forms, with or without
//  modification, are permitted provided that the following conditions
//  are met:
//
//     * Redistributions of source code must retain the above
//       copyright notice, this list of conditions and the following
//       disclaimer.
//
//     * Redistributions in binary form must reproduce the above
//       copyright notice, this list of conditions and the following
//       disclaimer in the documentation and/or other materials
//       provided with the distribution.
//
//     * Neither the name of the software nor the names of its
//       contributors may be used to endorse or promote products
//       derived from this software without specific prior written
//       permission.
// 
//  THIS SOFTWARE IS PROVIDED BY Jim Hourihan ''AS IS'' AND ANY EXPRESS
//  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
//  ARE DISCLAIMED. IN NO EVENT SHALL Jim Hourihan BE LIABLE FOR
//  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
//  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
//  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
//  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
//  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
//  DAMAGE.
//
#ifndef __MuQt__QLabelType__h__
#define __MuQt__QLabelType__h__
#include <iostream>
#include <Mu/Class.h>
#include <Mu/Process.h>
#include <QtCore/QtCore>
#include <QtGui/QtGui>
#include <QtNetwork/QtNetwork>
#include <QtWebKit/QtWebKit>
#include <QtSvg/QtSvg>
#include <MuQt/Bridge.h>

namespace Mu {
class MuQt_QLabel;

//
//  NOTE: file generated by qt2mu.py
//

class QLabelType : public Class
{
  public:

    typedef MuQt_QLabel MuQtType;
    typedef QLabel QtType;

    //
    //  Constructors
    //

    QLabelType(Context* context, 
           const char* name,
           Class* superClass = 0,
           Class* superClass2 = 0);

    virtual ~QLabelType();

    static bool isInheritable() { return true; }
    static inline ClassInstance* cachedInstance(const MuQtType*);

    //
    //  Class API
    //

    virtual void load();

    MemberFunction* _func[14];
};

// Inheritable object

class MuQt_QLabel : public QLabel
{
  public:
    virtual ~MuQt_QLabel();
    MuQt_QLabel(Pointer muobj, const CallEnvironment*, QWidget * parent, Qt::WindowFlags f) ;
    MuQt_QLabel(Pointer muobj, const CallEnvironment*, const QString & text, QWidget * parent, Qt::WindowFlags f) ;
    virtual int heightForWidth(int w) const;
    virtual QSize minimumSizeHint() const;
    virtual QSize sizeHint() const;
  protected:
    virtual void changeEvent(QEvent * ev) ;
    virtual void contextMenuEvent(QContextMenuEvent * ev) ;
    virtual bool event(QEvent * e) ;
    virtual void focusInEvent(QFocusEvent * ev) ;
    virtual bool focusNextPrevChild(bool next) ;
    virtual void focusOutEvent(QFocusEvent * ev) ;
    virtual void keyPressEvent(QKeyEvent * ev) ;
    virtual void mouseMoveEvent(QMouseEvent * ev) ;
    virtual void mousePressEvent(QMouseEvent * ev) ;
    virtual void mouseReleaseEvent(QMouseEvent * ev) ;
    virtual void paintEvent(QPaintEvent * _p15) ;
  public:
    void changeEvent_pub(QEvent * ev)  { changeEvent(ev); }
    void changeEvent_pub_parent(QEvent * ev)  { QLabel::changeEvent(ev); }
    void contextMenuEvent_pub(QContextMenuEvent * ev)  { contextMenuEvent(ev); }
    void contextMenuEvent_pub_parent(QContextMenuEvent * ev)  { QLabel::contextMenuEvent(ev); }
    bool event_pub(QEvent * e)  { return event(e); }
    bool event_pub_parent(QEvent * e)  { return QLabel::event(e); }
    void focusInEvent_pub(QFocusEvent * ev)  { focusInEvent(ev); }
    void focusInEvent_pub_parent(QFocusEvent * ev)  { QLabel::focusInEvent(ev); }
    bool focusNextPrevChild_pub(bool next)  { return focusNextPrevChild(next); }
    bool focusNextPrevChild_pub_parent(bool next)  { return QLabel::focusNextPrevChild(next); }
    void focusOutEvent_pub(QFocusEvent * ev)  { focusOutEvent(ev); }
    void focusOutEvent_pub_parent(QFocusEvent * ev)  { QLabel::focusOutEvent(ev); }
    void keyPressEvent_pub(QKeyEvent * ev)  { keyPressEvent(ev); }
    void keyPressEvent_pub_parent(QKeyEvent * ev)  { QLabel::keyPressEvent(ev); }
    void mouseMoveEvent_pub(QMouseEvent * ev)  { mouseMoveEvent(ev); }
    void mouseMoveEvent_pub_parent(QMouseEvent * ev)  { QLabel::mouseMoveEvent(ev); }
    void mousePressEvent_pub(QMouseEvent * ev)  { mousePressEvent(ev); }
    void mousePressEvent_pub_parent(QMouseEvent * ev)  { QLabel::mousePressEvent(ev); }
    void mouseReleaseEvent_pub(QMouseEvent * ev)  { mouseReleaseEvent(ev); }
    void mouseReleaseEvent_pub_parent(QMouseEvent * ev)  { QLabel::mouseReleaseEvent(ev); }
    void paintEvent_pub(QPaintEvent * _p15)  { paintEvent(_p15); }
    void paintEvent_pub_parent(QPaintEvent * _p15)  { QLabel::paintEvent(_p15); }
  public:
    const QLabelType* _baseType;
    ClassInstance* _obj;
    const CallEnvironment* _env;
};

inline ClassInstance* QLabelType::cachedInstance(const QLabelType::MuQtType* obj) { return obj->_obj; }

} // Mu

#endif // __MuQt__QLabelType__h__
