#  -*- mode: makefile -*-

PROJECT		= test
TYPE		= PLUGIN
PLUGIN_DIR	= plugins/Mu
PLUGINSUFFIX	= .so
IPATH		= $(SRC_ROOT)/pub/gc

CXXFILES	= init TestModule SequenceInterface BaseType  \
		  AClassType BClassType CClassType BarInterface

include $(SRC_ROOT)/build/Makefile.master
