#  -*- mode: makefile -*-


PROJECT     = MuGelato
TYPE        = LIBRARY

CXXFILES    = GelatoModule
LIBS        =

IPATH       += $(GELATOHOME)/include /usr/X11R6/include
LPATH       += $(GELATOHOME)/lib /usr/X11R6/lib


include $(SRC_ROOT)/build/Makefile.master
