#  -*- mode: makefile -*-

PROJECT		= gl
TYPE		= PLUGIN
PLUGIN_DIR	= plugins/Mu
PLUGINSUFFIX	= .so
IPATH		= $(SRC_ROOT)/pub/gc

FRAMEWORKS_DARWIN = OpenGL

CXXFILES	= init
LIBS            = MuGL 
LIBS_LINUX	= GL

include $(SRC_ROOT)/build/Makefile.master
