#  -*- mode: makefile -*-

PROJECT		= math_linear
TYPE		= PLUGIN
PLUGIN_DIR	= plugins/Mu
PLUGINSUFFIX	= .so

IPATH		+= $(SRC_ROOT)/pub/gc 

CXXFILES	= init
LIBS            = MuMathLinear

include $(SRC_ROOT)/build/Makefile.master
