#  -*- mode: makefile -*-

PROJECT		= image
TYPE		= PLUGIN
PLUGIN_DIR	= plugins/Mu
PLUGINSUFFIX	= .so
IPATH		= $(SRC_ROOT)/pub/gc

CXXFILES	= init
LIBS            = MuImage tiff jpeg cv cxcore z

include $(SRC_ROOT)/build/Makefile.master
