#  -*- mode: makefile -*-

PROJECT		= python
TYPE		= PLUGIN
PLUGIN_DIR	= plugins/Mu
PLUGINSUFFIX	= .so
IPATH		= $(SRC_ROOT)/pub/gc

USES            = python

CXXFILES	= init
LIBS            = MuPy

include $(SRC_ROOT)/build/Makefile.master
