#  -*- mode: makefile -*-

PROJECT		= encoding
TYPE		= PLUGIN
PLUGIN_DIR	= plugins/Mu
PLUGINSUFFIX	= .so

IPATH		+= $(SRC_ROOT)/pub/gc 

CXXFILES	= init
LIBS            = MuEncoding 

include $(SRC_ROOT)/build/Makefile.master
